VideoSIte/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoSIte.Models;
using VideoSIte.ViewModels;

namespace VideoSIte.Controllers
{
    public class VideosController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Videos
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult _CategoryList()
        {
            var categoryList = db.Categories.OrderBy(x => x.CatName).ToList();
            return PartialView(categoryList);
        }

        public PartialViewResult _VideoList(int? category)
        {
            if (category != null)
            {
                var videosList = db.Videos.OrderByDescending(a => a.VideoId)
                                          .Where(a => a.Categories
                                          .Any(c => c.CatId == category))
                                          .ToList();
                return PartialView(videosList);
            }
            else
            {
                var videosList = db.Videos.OrderByDescending(a => a.VideoId).ToList();
                return PartialView(videosList);
            }
        }
        public PartialViewResult _RelatedVideosList(int? id)
        {
            var videos = db.Videos.SqlQuery("[dbo].[spGetRelatedVideos] @VideoId", new SqlParameter("VideoId", id))
                                  .Where(x => x.VideoId != id).Take(5).ToList();
            return PartialView(videos);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var video = db.Videos.SingleOrDefault(c => c.VideoId == id);

            video.Products = GetProductByVideoId(id);

            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }
        public ICollection<Product> GetProductByVideoId(int? videoId)
        {
            ICollection<Product> products = new List<Product>();
            
            return products;
        }
    }
}

VideoSIte/Views/Shared/VideoListPartial.cshtml
@model IEnumerable<VideoSIte.Models.Video>


@for (int i = 0; i < Model.Count(); i += 3)
{
    <div class="container">
        <div class="row">
            @foreach (var item in Model.Skip(i).Take(3))
            {
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <iframe width="350" height="250"
                                src="https://www.youtube.com/embed/@item.VideoUrlId"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen></iframe>
                        <div class="caption">
                            <h3>@item.VideoName</h3>
                            <p>
                                <a href="@Url.Action("Details", "Videos", new { id = item.VideoId })"
                                    class="btn btn-primary" role="button">More</a>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>          
}

VideoSIte/Views/Shared/_CategoryList.cshtml
@model IEnumerable<VideoSIte.Models.Category>

<div class="container-fluid">
    <div class="row">
        <ul class="nav nav-pills nav-stacked">
            <li>@Html.ActionLink("All", "Index", "Videos")</li>
            @foreach (var item in Model)
            {
                <li>@Html.ActionLink(item.CatName, "Index", "Videos", new { category = item.CatId }, null)</li>
            }
        </ul>
    </div>
</div>

VideoSIte/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Video Site", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area=string.Empty}, null)</li>
                    <li>@Html.ActionLink("Videos", "Index", "Videos", new { area=string.Empty}, null)</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area=string.Empty}, null)</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area=string.Empty}, null)</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Admin", "Index", "Admin/UserAdmin", new { area=string.Empty}, null)</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

VideoSIte/Views/Shared/_VideoList.cshtml
@model IEnumerable<VideoSIte.Models.Video>

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-3 col-md-4">
                <div class="thumbnail">
                    <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item"
                                src="https://www.youtube.com/embed/@item.VideoUrlId"
                                frameborder="0"
                                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                        </iframe>
                    </div>
                    <div class="caption">
                        <h3>@item.VideoName</h3>
                        <p>
                            <a href="@Url.Action("Details", "Videos", new { id = item.VideoId })"
                                class="btn btn-primary" role="button">More</a>
                        </p>
                    </div>
                </div>
            </div>
        }
    </div>
</div> 