VideoSIte/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;


namespace VideoSIte.Models
{
    public class UserViewModel
    {
        public string Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }

    }
    public class EditViewModel
    {
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public IEnumerable<SelectListItem> RolesList { get; set; }
    }
}

VideoSIte/Areas/admin/Controllers/UserAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VideoSIte.Models;

namespace VideoSIte.Areas.admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin
        public ActionResult Index()
        {
            var usersWithRoles = (from user in db.Users
                                  select new
                                  {
                                      id = user.Id,
                                      Username = user.UserName,
                                      Email = user.Email,
                                      RoleNames = (from userRole in user.Roles
                                                   join role in db.Roles on userRole.RoleId equals role.Id
                                                   select role.Name).ToList()
                                  }).ToList().Select(p => new UserViewModel()

                                  {
                                      Id = p.id,  
                                      Username = p.Username,
                                      Email = p.Email,
                                      Role = string.Join(",", p.RoleNames)
                                  });

            return View(usersWithRoles);
        }
        public ActionResult CreateUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateUser(FormCollection form)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string userName = form["txtEmail"];
            string email = form["txtEmail"];
            string pwd = form["txtPassword"];

            //Create Default Users
            var user = new ApplicationUser();
            user.UserName = userName;
            user.Email = email;

            userManager.Create(user, pwd);

            return View("Index");
        }

        public ActionResult AssignRole()
        {
            ViewBag.Roles = db.Roles.Select(r => new SelectListItem { Value = r.Name, Text = r.Name }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignRole(FormCollection form)
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            string userName = form["txtUserName"];
            string roleName = form["RoleName"];
            ApplicationUser user = db.Users.Where(u => u.UserName.Equals(userName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

            userManager.AddToRole(user.Id, roleName);

            return RedirectToAction("Index");
        }
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userdetail = this.db.UserDetails.FirstOrDefault(p => p.Id == id);
            if (userdetail == null)
            {
                return HttpNotFound();
            }

            return View(userdetail);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include ="Id,FirstName,LastName,Address,City")]UserDetail model)
        {            
            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
            }

            return View();
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDetail userdetail = this.db.UserDetails.FirstOrDefault(p => p.Id == id);
            if (userdetail == null)
            {
                return HttpNotFound();
            }

            return View(userdetail);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

VideoSIte/Areas/admin/Views/UserAdmin/AssignRole.cshtml
@{
    ViewBag.Title = "AssignRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Assign Role</h2>

@using (Html.BeginForm("AssignRole", "UserAdmin", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <label class="control-label">User Name</label>
            <input type="text" name="txtUserName" class="form-control" />
        </div>
        <div class="col-md-6">
            <label class="control-label">Select Role</label>
            @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select..")
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-lg-12">
            <button class="btn btn-primary" type="submit">Save</button>
        </div>
    </div>
}

VideoSIte/Areas/admin/Views/UserAdmin/CreateUser.cshtml
@{
    ViewBag.Title = "CreateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create User</h2>

@using (Html.BeginForm("CreateUser", "UserAdmin", FormMethod.Post))

{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <label class="control-label">User Email</label>
            <input type="text" name="txtEmail" class="form-control" />
        </div>
        <div class="col-md-6">
            <label class="control-label">Password</label>
            <input type="password" name="txtPassword" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button type="submit" value="Submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

<div class="row">
    @Html.ActionLink("Back to List", "Index")
</div>

VideoSIte/Areas/admin/Views/UserAdmin/Details.cshtml
@model VideoSIte.Models.UserDetail

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName,"First Name")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName,"Last Name")
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VideoSIte/Areas/admin/Views/UserAdmin/Edit.cshtml
@model VideoSIte.Models.UserDetail

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4></h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName,"First Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName,"Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
        @Html.Label("Roles", new { @class = "control-label col-md-2" })
        <span class=" col-md-10">
            @foreach (var item in Model.RolesList)
            {
                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </span>
    </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VideoSIte/Areas/admin/Views/UserAdmin/Index.cshtml
@model IEnumerable<VideoSIte.Models.UserViewModel>

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Dashboard</h2>

<ul class="nav nav-pills">
    <li role="presentation" class="active"><a href="~/admin/UserAdmin/Index/">User</a></li>
    <li role="presentation"><a href="~/admin/Videos/Index/">Videos</a></li>
    <li role="presentation"><a href="~/admin/Categories/Index/">Categories</a></li>
    <li role="presentation"><a href="~/admin/Products/Index/">Products</a></li>
</ul>

<p>
    @Html.ActionLink("Create New", "CreateUser")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id}) |
                @Html.ActionLink("Details", "Details", new { id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<ul>
    <li>@Html.ActionLink("Edit Role", "AssignRole")</li>

</ul>

VideoSIte/Areas/admin/Views/UserAdmin/UserView.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Admin </h2>

@model IEnumerable<VideoSIte.Models.UserViewModel>
<div class="row">
    <h4>Users</h4>

    @foreach (var user in Model ?? Enumerable.Empty<dynamic>())
    {
        <p>
            <strong>
                @user.Username | @user.Email | @user.Role
            </strong>
        </p>
    }
</div>

<ul>
    <li>@Html.ActionLink("Create User", "CreateUser", "Admin")</li>
    <li>@Html.ActionLink("Assign Role", "AssignRole", "Admin")</li>

</ul>